export const GEOM = {
    BOX: 'BOX',
    CYLINDER: 'CYLINDER',
    DISC: 'DISC',
    ICOSPHERE: 'ICOSPHERE',
    PLANE: 'PLANE',
    POLYHEDRON: 'POLYHEDRON',
    TORUS: 'TORUS',
    TUBE: 'TUBE',
    RIBBON: 'RIBBON',
    SPHERE: 'SPHERE',
};

export const LIGHT = {
    DIRECTIONAL: 'DIRECTIONAL',
    SPOT: 'SPOT',
    POINT: 'POINT',
    HEMISPHERIC: 'HEMISPHERIC'
};